require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ToysController do

  # This should return the minimal set of attributes required to create a valid
  # Toy. As you add validations to Toy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all toys as @toys" do
      toy = Toy.create! valid_attributes
      get :index
      assigns(:toys).should eq([toy])
    end
  end

  describe "GET show" do
    it "assigns the requested toy as @toy" do
      toy = Toy.create! valid_attributes
      get :show, :id => toy.id
      assigns(:toy).should eq(toy)
    end
  end

  describe "GET new" do
    it "assigns a new toy as @toy" do
      get :new
      assigns(:toy).should be_a_new(Toy)
    end
  end

  describe "GET edit" do
    it "assigns the requested toy as @toy" do
      toy = Toy.create! valid_attributes
      get :edit, :id => toy.id
      assigns(:toy).should eq(toy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Toy" do
        expect {
          post :create, :toy => valid_attributes
        }.to change(Toy, :count).by(1)
      end

      it "assigns a newly created toy as @toy" do
        post :create, :toy => valid_attributes
        assigns(:toy).should be_a(Toy)
        assigns(:toy).should be_persisted
      end

      it "redirects to the created toy" do
        post :create, :toy => valid_attributes
        response.should redirect_to(Toy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved toy as @toy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Toy.any_instance.stub(:save).and_return(false)
        post :create, :toy => {}
        assigns(:toy).should be_a_new(Toy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Toy.any_instance.stub(:save).and_return(false)
        post :create, :toy => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested toy" do
        toy = Toy.create! valid_attributes
        # Assuming there are no other toys in the database, this
        # specifies that the Toy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Toy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => toy.id, :toy => {'these' => 'params'}
      end

      it "assigns the requested toy as @toy" do
        toy = Toy.create! valid_attributes
        put :update, :id => toy.id, :toy => valid_attributes
        assigns(:toy).should eq(toy)
      end

      it "redirects to the toy" do
        toy = Toy.create! valid_attributes
        put :update, :id => toy.id, :toy => valid_attributes
        response.should redirect_to(toy)
      end
    end

    describe "with invalid params" do
      it "assigns the toy as @toy" do
        toy = Toy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Toy.any_instance.stub(:save).and_return(false)
        put :update, :id => toy.id, :toy => {}
        assigns(:toy).should eq(toy)
      end

      it "re-renders the 'edit' template" do
        toy = Toy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Toy.any_instance.stub(:save).and_return(false)
        put :update, :id => toy.id, :toy => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested toy" do
      toy = Toy.create! valid_attributes
      expect {
        delete :destroy, :id => toy.id
      }.to change(Toy, :count).by(-1)
    end

    it "redirects to the toys list" do
      toy = Toy.create! valid_attributes
      delete :destroy, :id => toy.id
      response.should redirect_to(toys_url)
    end
  end

end
